import test from 'node:test';import assert from 'node:assert/strict';
import {newJourney,mark,collect,decide} from '../src/state';import {rooms} from '../src/world';import {headquartersRooms,projectAccepted,projectStatus,canArchive,encounter} from '../src/headquarters';import {areas,areaOf} from '../src/Atlas';
test('headquarters has five purposeful rooms, with committee and partner in their own rooms',()=>{assert.equal(headquartersRooms.length,5);assert.equal(newJourney().scene,'study');assert.ok(rooms.study.entities.some(e=>e.kind==='projects'));assert.ok(rooms.archive.entities.some(e=>e.kind==='archive'));assert.ok(rooms.meeting.entities.some(e=>e.kind==='committee'));assert.ok(rooms.partnerroom.entities.some(e=>e.person==='partner'));assert.ok(!rooms.fund.entities.some(e=>e.person==='partner'||e.kind==='committee'))});
test('every room belongs to exactly one physical location, across-site travel is distinguishable',()=>{const all=Object.values(areas).flatMap(a=>a.rooms);assert.equal(new Set(all).size,all.length);assert.deepEqual([...all].sort(),Object.keys(rooms).sort());assert.equal(areaOf('fund'),areaOf('study'));assert.notEqual(areaOf('fund'),areaOf('office'));assert.notEqual(areaOf('office'),areaOf('client'))});
test('new mandates require acceptance while existing investigations remain usable',()=>{const j=newJourney();assert.equal(projectAccepted(j),false);assert.equal(projectAccepted(mark(j,'project-accepted')),true);assert.equal(projectAccepted(collect(j,'memo')),true);assert.equal(projectAccepted({...j,scene:'office'}),true);assert.equal(j.projectId,'relayops')});
test('archive requires a signed decision and all replies; independent journeys retain independent evidence',()=>{let j=mark(collect(newJourney(),'memo'),'met-partner');assert.equal(canArchive(j),false);j=decide(j,'pause');assert.equal(canArchive(j),false);for(const id of ['echo-founder','echo-finance','echo-client'])j=mark(j,id);assert.equal(canArchive(j),true);j=mark(j,'case-archived');assert.equal(projectStatus(j)[1],'Archived');assert.equal(newJourney().save.facts['case-archived'],undefined)});
test('colleagues and existing contacts never receive a visitor-badge introduction',()=>{for(const id of ['partner','analyst','founder'] as const){const copy=JSON.stringify(encounter[id]);assert.ok(!/visitor|badge|访客|Introduce yourself/.test(copy),id)}});
import {archiveJourney} from '../src/state';
test('archive command rejects incomplete cases and is idempotent after completion',()=>{let j=newJourney();assert.equal(archiveJourney(j),j);j=decide(mark(collect(j,'memo'),'met-partner'),'pause');for(const f of ['echo-founder','echo-finance','echo-client'])j=mark(j,f);const archived=archiveJourney(j);assert.ok(archived.save.facts['case-archived']);assert.equal(archiveJourney(archived),archived)});
