import {chromium} from 'playwright';import assert from 'node:assert/strict';
const base=process.env.QA_URL||'http://127.0.0.1:5225/';const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
async function run(w,h){const context=await browser.newContext({viewport:{width:w,height:h}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',route=>route.abort());await page.goto(base);await page.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});await page.getByRole('button',{name:'Take your badge. Begin.'}).click();await page.locator('.bc-world-loading').waitFor({state:'detached'});await page.getByRole('button',{name:'Menu',exact:true}).click();await page.getByRole('button',{name:'中文 / English',exact:true}).click();await page.getByRole('button',{name:'关闭 / Close',exact:true}).click();await page.locator('.bc-modal').waitFor({state:'detached'});const capture=async name=>{await page.locator('.bc-world-loading').waitFor({state:'detached'});await page.waitForTimeout(250);await page.screenshot({path:`_qa/ui/platform-layout-${name}-${w}x${h}.png`})};
async function reach(id){await page.waitForTimeout(100);await page.locator('.bc-world-loading').waitFor({state:'detached'});console.log(JSON.stringify({width:w,reaching:id}));const b=page.locator(`[data-entity="${id}"]`);await b.focus();await b.press('Enter');await page.waitForFunction(id=>{const el=document.querySelector(`[data-entity="${id}"]`);const primary=document.querySelector('.bc-primary');return primary?.getAttribute('data-active')==='true'&&primary.textContent.includes(el?.textContent||'__')},id,{timeout:20000});await page.locator('.bc-primary').click()}
async function close(){await page.getByRole('button',{name:'结束查看',exact:true}).click()}
async function finishReply(){await page.waitForTimeout(500);for(let n=0;n<10;n++){const b=page.locator('.bc-turn .bc-solid');if(!await b.count())break;await b.click()} }
async function meet(id){await reach(id);if(await page.getByRole('button',{name:'打招呼，说明来意'}).count()){await page.getByRole('button',{name:'打招呼，说明来意'}).click();await finishReply();const bounds=await page.locator('.bc-topics > button').evaluateAll(es=>es.slice(0,2).map(e=>{const r=e.getBoundingClientRect(),p=e.closest('.bc-interaction-body').getBoundingClientRect();return {top:r.top,bottom:r.bottom,limit:p.bottom}}));assert.ok(bounds.length>=1);for(const b of bounds)assert.ok(b.bottom<=b.limit+1,JSON.stringify(b))} }
async function record(id){await reach(id);await page.getByRole('button',{name:'展开完整资料'}).click();assert.ok((await page.locator('.bc-document').innerText()).length>80);await page.getByRole('button',{name:'关闭 / Close',exact:true}).click();await close()}
await capture('fund');await record('memo');await meet('partner');await capture('conversation');await page.getByRole('button',{name:'放大头像'}).click();await capture('portrait');await page.getByRole('button',{name:'关闭 / Close',exact:true}).click();await close();await meet('analyst');await close();await reach('fund-office');await page.locator('.bc-location').filter({hasText:'RelayOps'}).waitFor();await capture('office');await record('contract');await record('forecast');await meet('founder');await close();await reach('office-records');await record('payment');await record('appendix');await record('cash');await record('channel');await meet('finance');await capture('data-room');await close();await reach('records-office');await reach('office-client');await record('rollout');await record('acceptance');await record('reference');await meet('client');await page.getByRole('button',{name:'你会签第二阶段验收吗？'}).click();await finishReply();await capture('client');await close();
await page.getByRole('button',{name:'资料',exact:true}).click();await page.getByRole('button',{name:'判断',exact:true}).click();for(const [idx,labels,answer] of [[0,['Harbor & Pine主合同','门店上线清单'],'合同已签，规模化仍待验证'],[1,['首款银行回单','项目补充协议'],'到账属实，但留存附履约条件'],[2,['未来四周付款排期','融资用途与现金预测'],'先补近期缺口，再保障交付']]){await page.getByRole('button',{name:'开始核对'}).first().click();for(const name of labels)await page.locator('.bc-source-picks').getByRole('button',{name,exact:true}).click();await page.getByRole('button',{name:answer,exact:true}).click();await page.locator('.bc-compare').waitFor({state:'detached'})}await capture('findings');await page.getByRole('button',{name:'关闭 / Close',exact:true}).click();await reach('client-office');await meet('founder');await page.getByRole('button',{name:w===320?'重定价与用途约束':'分期交割与现金披露',exact:true}).click();await finishReply();await capture('negotiation');await close();await reach('office-fund');await reach('committee');await page.getByRole('button',{name:'按协商条件推进',exact:true}).click();await page.getByRole('button',{name:'签署意见',exact:true}).click();await capture('ending');assert.match(await page.locator('.bc-panel-body').innerText(),/你改变了交易条件/);await page.getByRole('button',{name:'回到现场复查'}).click();await page.reload();await page.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});assert.equal(await page.getByRole('button',{name:'拿起访客证，开始调查'}).count(),0);await reach('committee');assert.match(await page.locator('.bc-panel-body').innerText(),/你改变了交易条件/);await page.getByRole('button',{name:'回到现场复查'}).click();await page.getByRole('button',{name:'菜单',exact:true}).click();await page.getByRole('button',{name:'中文 / English',exact:true}).click();await capture('english-menu');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log(JSON.stringify({width:w,height:h,passed:true}));await context.close()}
try{await run(390,844);await run(320,568)}finally{await browser.close()}
