import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});await context.addInitScript(()=>{window.__sounds=[];const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){window.__sounds.push({src:this.src,volume:this.volume,time:performance.now()});return play.call(this)}});const page=await context.newPage();const base=process.env.QA_URL||'http://127.0.0.1:5225/';const report={};
async function reach(id){const b=page.locator(`[data-entity="${id}"]`);await b.focus();await b.press('Enter');await page.waitForFunction(id=>{const e=document.querySelector(`[data-entity="${id}"]`);return document.querySelector('.bc-primary')?.textContent.includes(e.textContent)},id);await page.locator('.bc-primary').click()}
try{await page.goto(base);await page.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});await page.getByRole('button',{name:'拿起访客证，开始调查'}).click();await page.locator('.bc-world-loading').waitFor({state:'detached'});await page.waitForTimeout(400);const start=await page.locator('[data-entity="analyst"]').boundingBox();await page.waitForTimeout(1000);const moved=await page.locator('[data-entity="analyst"]').boundingBox();assert.ok(Math.abs(moved.x-start.x)>4);report.patrol=true;
const count=()=>page.evaluate(()=>window.__sounds.filter(x=>x.src.endsWith('/step.mp3')).length);await page.keyboard.down('ArrowRight');await page.waitForTimeout(600);await page.keyboard.up('ArrowRight');assert.ok(await count()>0);const still=await count();await page.waitForTimeout(800);assert.equal(await count(),still);await page.getByRole('button',{name:'声音',exact:true}).click();await page.keyboard.down('ArrowLeft');await page.waitForTimeout(600);await page.keyboard.up('ArrowLeft');assert.equal(await count(),still);report.actualDistanceAndMute=true;report.audioBeforeReload=await page.evaluate(()=>window.__sounds);await page.getByRole('button',{name:'声音',exact:true}).click();
await reach('memo');await page.getByRole('button',{name:'结束查看',exact:true}).click();await reach('partner');await page.getByRole('button',{name:'打招呼，说明来意'}).click();await page.waitForTimeout(500);while(await page.locator('.bc-turn .bc-solid').count())await page.locator('.bc-turn .bc-solid').click();await page.getByRole('button',{name:'结束查看',exact:true}).click();
await page.getByRole('button',{name:'地图',exact:true}).click();await page.screenshot({path:'_qa/ui/platform-layout-map-390x844.png'});await page.getByRole('button',{name:'关闭 / Close'}).click();await reach('committee');await page.getByRole('button',{name:'按原条件推进',exact:true}).click();await page.getByRole('button',{name:'签署意见',exact:true}).click();await page.screenshot({path:'_qa/ui/platform-layout-original-terms-390x844.png'});assert.match(await page.locator('.bc-result-title').innerText(),/原条件/);await page.getByRole('button',{name:'回到现场复查'}).click();const original=await page.evaluate(()=>JSON.parse(alteruLocalStorage.getItem('before-the-close')));assert.equal(original.journeys[0].save.facts.decision,'proceed');
await page.getByRole('button',{name:'菜单',exact:true}).click();await page.getByRole('button',{name:'新开一次调查，保留本次',exact:true}).click();await page.getByRole('button',{name:'拿起访客证，开始调查'}).click();await page.waitForTimeout(200);let state=await page.evaluate(()=>JSON.parse(alteruLocalStorage.getItem('before-the-close')));assert.equal(state.journeys.length,2);assert.equal(state.journeys[0].save.facts.memo,undefined);assert.equal(state.journeys[1].save.facts.decision,'proceed');report.journeyIsolation=true;
// QA fixture only: exercise the second terminal branch without repeating all walking.
await page.evaluate(()=>window.addEventListener('pagehide',()=>{const s=JSON.parse(alteruLocalStorage.getItem('before-the-close'));s.journeys[0].save.facts.memo=true;s.journeys[0].save.facts['met-partner']=true;alteruLocalStorage.setItem('before-the-close',JSON.stringify(s))}));await page.reload();await page.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});await page.locator('.bc-world-loading').waitFor({state:'detached'});await reach('committee');await page.getByRole('button',{name:'建议暂停交割',exact:true}).click();await page.getByRole('button',{name:'签署意见',exact:true}).click();assert.match(await page.locator('.bc-result-title').innerText(),/暂停/);report.pauseBranch='UI with explicit prerequisite fixture';
await page.evaluate(()=>window.addEventListener('pagehide',()=>alteruLocalStorage.setItem('before-the-close','{bad json')));await page.reload();assert.equal(await page.getByText('暂时无法读取旧进度',{exact:true}).count(),1);assert.equal(await page.evaluate(()=>alteruLocalStorage.getItem('before-the-close')),'{bad json');await page.getByRole('button',{name:'保留备份，开始新调查'}).click();await page.getByRole('button',{name:'拿起访客证，开始调查'}).waitFor();report.corruptSaveRecovery=true;report.audio=await page.evaluate(()=>window.__sounds);await fs.writeFile('_qa/recovery-audio.json',JSON.stringify(report,null,2));console.log(report)}finally{await browser.close()}
