import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:3});const errors=[],logs=[],failed=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>logs.push(message.type()+': '+message.text()));page.on('response',response=>{if(response.status()>=400)failed.push({status:response.status(),url:response.url()})});
 await page.route('https://**',route=>route.abort());
 const target=new URL(process.env.QA_URL||'http://127.0.0.1:5226/');target.searchParams.set('debug','1');await page.goto(target.href);await page.addStyleTag({content:'#alteru-guest-banner{display:none!important}'});
 const start=page.getByRole('button',{name:'Take your badge. Begin.'});if(await start.count())await start.click();
 await page.locator('.bc-world-loading').waitFor({state:'detached',timeout:30000});await page.waitForTimeout(1500);
 const metrics=await page.evaluate(()=>{const world=document.querySelector('.bc-world').getBoundingClientRect(),node=document.querySelector('#rpg'),host=node.getBoundingClientRect(),canvas=document.querySelector('#rpg canvas').getBoundingClientRect(),rows=[],nodes=[];const seen=new Set();function visit(n,depth=0){if(!n||seen.has(n)||depth>20||seen.size>500)return;seen.add(n);nodes.push({type:n.constructor?.name,depth,x:n.x,y:n.y,children:n.children?.length,visible:n.visible,renderable:n.renderable,alpha:n.worldAlpha});if(n.texture)rows.push({x:n.x,y:n.y,sx:n.scale?.x,sy:n.scale?.y,visible:n.visible,renderable:n.renderable,alpha:n.worldAlpha,w:n.texture?.width,h:n.texture?.height});for(const c of n.children||[])visit(c,depth+1)}visit(node.__rpgClient?.canvasApp?.stage);const sprite=node.__rpgClient?.getCurrentPlayer(),sheet=sprite?.graphicsSignals()[0],engine=node.__rpgClient,scene=engine?.scene,count=x=>x instanceof Map||x instanceof Set?x.size:Array.isArray(x)?x.length:x&&typeof x==='object'?Object.keys(x).length:null,value=x=>typeof x==='function'?x():x,components=value(engine?.spriteComponents),entries=components instanceof Map?[...components.entries()]:Object.entries(components||{}),componentRows=entries.map(([key,item])=>({key,type:item?.constructor?.name,valueType:typeof item,keys:Object.keys(item||{})}));return{world:{w:world.width,h:world.height},host:{x:host.x-world.x,w:host.width,h:host.height},canvas:{x:canvas.x-world.x,w:canvas.width,h:canvas.height},events:document.querySelectorAll('[data-entity]').length,dataset:{...node.dataset},registrations:{players:count(value(scene?.__players)),events:count(value(scene?.__events)),spriteComponents:count(components),behind:count(value(engine?.spriteComponentsBehind)),front:count(value(engine?.spriteComponentsInFront))},componentRows,sheet:sheet?{id:sheet.id,image:sheet.image,width:sheet.width,height:sheet.height,textures:Object.keys(sheet.textures||{}),frame:sheet.textures?.stand?.animations?.({direction:'down'})}:null,engineSheets:[...(engine?.spritesheets?.keys?.()||[])],player:sprite?{id:sprite.id,x:sprite.x(),y:sprite.y(),direction:sprite.direction(),animation:sprite.animationName(),connected:sprite.isConnected(),graphics:sprite.graphics()}:null,textures:rows.slice(0,20),nodes:nodes.slice(0,40)}});
 await page.screenshot({path:'_qa/ui/platform-layout-rpg-smoke-390x844.png'});
 assert.equal(errors.length,0,errors.join('\n'));assert.ok(metrics.canvas.w>360,JSON.stringify(metrics));assert.equal(metrics.registrations.players,1,JSON.stringify(metrics));assert.ok(metrics.registrations.events>=6,JSON.stringify(metrics));assert.ok(metrics.textures.length>=8,JSON.stringify(metrics));console.log(JSON.stringify({...metrics,failed,logs}));
}finally{await browser.close()}
