import {useRef,useState} from 'react';
import {MapPin,ChevronRight,Building2,BriefcaseBusiness,Files,Store,LocateFixed,Maximize,Minus,Plus} from 'lucide-react';
import {rooms,type SceneId} from './world';import {tx,type Locale,type Pair} from './content';import doors from './door-layout.json';import {routeBetween} from './map-route';
import {areas,areaOf,type AreaId} from './locations';
export {areas,areaOf} from './locations';
const points:Record<SceneId,[number,number]>={partnerroom:[296,42],meeting:[296,118],fund:[296,194],study:[296,270],archive:[296,346],office:[166,270],records:[446,270],delivery:[166,90],client:[296,195],channel:[296,195]};
const mapLabels:Record<SceneId,Pair>={study:['我的办公室','Your office'],archive:['基金资料室','Fund archive'],partnerroom:['合伙人','Partner'],meeting:['投委会','Committee'],delivery:['交付作战室','Delivery'],channel:['渠道结算','Settlement'],fund:['项目组','Deal team'],office:['开放办公区','RelayOps'],records:['资料室','Data room'],client:['客户现场','Harbor & Pine']};
const icons={study:BriefcaseBusiness,archive:Files,partnerroom:BriefcaseBusiness,meeting:BriefcaseBusiness,delivery:Building2,channel:Files,fund:BriefcaseBusiness,office:Building2,records:Files,client:Store};
const edges=Object.values(rooms).flatMap(r=>r.entities.filter(e=>e.to).map(e=>({from:r.id,to:e.to!,id:e.id})));
export function Atlas({scene,locale}:{scene:SceneId;locale:Locale}){
 const t=(p:Pair)=>tx(p,locale),[destination,setDestination]=useState(scene),[area,setArea]=useState<AreaId>(areaOf(scene)),[overview,setOverview]=useState(false),[view,setView]=useState({x:0,y:0,z:1});
 const viewport=useRef<HTMLDivElement>(null),pointers=useRef(new Map<number,{x:number;y:number}>()),moved=useRef(false);
 const route=routeBetween(scene,destination,edges),steps=route?.slice(1).map((to,i)=>({from:route[i],to}))||[];
 const change=(x:number,y:number,z:number)=>setView({x:Math.max(-300,Math.min(300,x)),y:Math.max(-240,Math.min(240,y)),z:Math.max(1,Math.min(2.5,z))});
 const locate=()=>{setArea(areaOf(scene));setOverview(false);const el=viewport.current;if(!el)return;const [x,y]=points[scene];change((.5-x/592)*el.clientWidth*1.7,(.5-y/390)*el.clientHeight*1.7,1.7)};
 const instruction=(from:SceneId,to:SceneId)=>{if(areaOf(from)!==areaOf(to))return t([`从${tx(areas[areaOf(from)].title,locale)}的外访出口出发，前往${tx(areas[areaOf(to)].title,locale)}。`,`Leave ${tx(areas[areaOf(from)].title,locale)} via its visit exit and travel to ${tx(areas[areaOf(to)].title,locale)}.`]);const edge=edges.find(e=>e.from===from&&e.to===to)!;const side=doors[edge.id as keyof typeof doors].side;const word=({N:['上方','top'],S:['下方','bottom'],W:['左侧','left'],E:['右侧','right']} as Record<string,Pair>)[side];return t([`从${tx(rooms[from].title,locale)}${word[0]}的门前往${tx(rooms[to].title,locale)}`,`From ${tx(rooms[from].title,locale)}, take the ${word[1]} door to ${tx(rooms[to].title,locale)}.`])};
 return <div className="bc-atlas"><div className="bc-atlas-location"><LocateFixed/><span>{t(['你在这里','YOU ARE HERE'])}<strong>{t(rooms[scene].title)}</strong></span></div>
 <button className="bc-area-switch" onClick={()=>setOverview(v=>!v)}>{t(overview?['返回地点内部图','Back to room map']:['地点总览 · 切换地图','Locations · Switch map'])}<MapPin/></button>
 {overview?<section className="bc-area-list">{(Object.keys(areas) as AreaId[]).map(id=><button key={id} onClick={()=>{setArea(id);setDestination(areas[id].rooms.includes(scene)?scene:areas[id].rooms[0]);setView({x:0,y:0,z:1});setOverview(false)}}><Building2/><span><strong>{t(areas[id].title)}</strong><small>{areas[id].rooms.length} {t(['个房间',areas[id].rooms.length===1?'room':'rooms'])}{id===areaOf(scene)?t([' · 你在这里',' · You are here']):''}</small></span><ChevronRight/></button>)}</section>:<>
 <h3 className="bc-area-title">{t(areas[area].title)}</h3><nav className="bc-atlas-tools" aria-label={t(['地图操作','Map controls'])}><button onClick={()=>change(0,0,1)}><Maximize/>{t(['全图','Fit'])}</button><button onClick={locate}><LocateFixed/>{t(['定位','Locate'])}</button><button aria-label={t(['缩小地图','Zoom out'])} disabled={view.z<=1} onClick={()=>change(view.x,view.y,view.z-.25)}><Minus/></button><button aria-label={t(['放大地图','Zoom in'])} disabled={view.z>=2.5} onClick={()=>change(view.x,view.y,view.z+.25)}><Plus/></button></nav>
 <p className="bc-atlas-hint">{t(['拖动查看 · 双指缩放 · 点选地点查看路线','Drag · Pinch to zoom · Select a destination'])}</p>
 <div className={"bc-atlas-viewport"+(area==='northline'?' bc-atlas-viewport--hq':'')} ref={viewport} onPointerDown={e=>{if(!pointers.current.size)moved.current=false;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY})}} onPointerMove={e=>{const old=pointers.current.get(e.pointerId);if(!old)return;const other=[...pointers.current].find(([id])=>id!==e.pointerId)?.[1],dx=e.clientX-old.x,dy=e.clientY-old.y;if(Math.hypot(dx,dy)<3&&!moved.current&&!other)return;moved.current=true;e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(other){const before=Math.hypot(old.x-other.x,old.y-other.y);if(before)change(view.x,view.y,view.z*Math.hypot(e.clientX-other.x,e.clientY-other.y)/before)}else change(view.x+dx,view.y+dy,view.z)}} onPointerUp={e=>pointers.current.delete(e.pointerId)} onPointerCancel={e=>pointers.current.delete(e.pointerId)} onLostPointerCapture={e=>pointers.current.delete(e.pointerId)} onClickCapture={e=>{if(moved.current&&e.detail){e.preventDefault();e.stopPropagation()}}}>
 <div className="bc-atlas-world" style={{transform:`translate(${view.x}px,${view.y}px) scale(${view.z})`}}><svg viewBox="0 0 592 390" preserveAspectRatio="none" aria-hidden="true">{edges.filter(e=>e.from<e.to&&areaOf(e.from)===area&&areaOf(e.to)===area).map(e=>{const a=points[e.from],b=points[e.to],i=route?.indexOf(e.from)??-1,active=i>=0&&(route?.[i+1]===e.to||route?.[i-1]===e.to);return <path key={e.id} data-route={active} d={`M${a} L${b}`}/>})}</svg>
 {areas[area].rooms.map(id=>rooms[id]).map(room=>{const I=icons[room.id],p=points[room.id],step=route?.indexOf(room.id)??-1;return <button key={room.id} data-room={room.id} aria-current={room.id===scene?'location':undefined} aria-pressed={room.id===destination} onClick={()=>setDestination(room.id)} style={{left:p[0]/592*100+'%',top:p[1]/390*100+'%'}}><I/><strong>{t(mapLabels[room.id])}</strong>{step>0&&<small>{step}</small>}</button>})}</div></div><p className="bc-atlas-hint">{t(['实线表示同一地点内的门；外出拜访需经出口转场。','Lines connect rooms within this location. Visits to other sites leave through an exit.'])}</p></>}
 <section className="bc-atlas-directions" aria-live="polite"><small>{t(destination===scene?['当前位置','CURRENT LOCATION']:['目的地','DESTINATION'])}</small><h3>{t(rooms[destination].title)}</h3>{steps.length?<><p>{instruction(steps[0].from,steps[0].to)}</p>{steps.length>1&&<details key={destination}><summary>{t(['完整路线','Full route'])} · {steps.length}</summary><ol>{steps.map(s=><li key={s.from}>{instruction(s.from,s.to)}</li>)}</ol></details>}</>:<p>{t(['选择地点查看路线，收起地图后走到门口。','Choose a destination, then close the map and walk to its exit.'])}</p>}</section></div>
}
