import {useMapGesture} from './use-map-gesture';
import {mapTravelStatus} from './map-travel';import type {Journey} from './state';
import {useState} from 'react';
import {MapPin,ChevronRight,Building2,BriefcaseBusiness,Files,Store,LocateFixed,Maximize,Minus,Plus} from 'lucide-react';
import {rooms,type SceneId} from './world';import {tx,type Locale,type Pair} from './content';import doors from './door-layout.json';import {routeBetween} from './map-route';
import {areas,areaOf,type AreaId} from './locations';
export {areas,areaOf} from './locations';
const points:Record<SceneId,[number,number]>={lobby:[296,214],partnerroom:[484,320],meeting:[296,64],fund:[484,130],study:[108,320],archive:[108,130],office:[166,270],records:[446,270],delivery:[166,90],client:[296,195],channel:[296,195]};
const mapLabels:Record<SceneId,Pair>={lobby:['中央接待区','Reception'],study:['我的办公室','Your office'],archive:['基金资料室','Fund archive'],partnerroom:['合伙人','Partner'],meeting:['投委会','Committee'],delivery:['交付作战室','Delivery'],channel:['渠道结算','Settlement'],fund:['项目组','Deal team'],office:['开放办公区','RelayOps'],records:['资料室','Data room'],client:['客户现场','Harbor & Pine']};
const icons={lobby:Building2,study:BriefcaseBusiness,archive:Files,partnerroom:BriefcaseBusiness,meeting:BriefcaseBusiness,delivery:Building2,channel:Files,fund:BriefcaseBusiness,office:Building2,records:Files,client:Store};
const edges=Object.values(rooms).flatMap(r=>r.entities.filter(e=>e.to).map(e=>({from:r.id,to:e.to!,id:e.id})));
export function Atlas({journey,locale,onTravel}:{journey:Journey;locale:Locale;onTravel:(id:SceneId)=>void}){
 const scene=journey.scene,g=useMapGesture();
 const t=(p:Pair)=>tx(p,locale),[destination,setDestination]=useState(scene),[area,setArea]=useState<AreaId>(areaOf(scene)),[overview,setOverview]=useState(false);
 const route=routeBetween(scene,destination,edges),steps=route?.slice(1).map((to,i)=>({from:route[i],to}))||[];
 const locate=()=>{setArea(areaOf(scene));setOverview(false);requestAnimationFrame(()=>g.locate(points[scene][0]/592,points[scene][1]/390))};
 const status=mapTravelStatus(journey,destination);
 const instruction=(from:SceneId,to:SceneId)=>{const edge=edges.find(e=>e.from===from&&e.to===to)!;const side=doors[edge.id as keyof typeof doors].side;const word=({N:['上方','top'],S:['下方','bottom'],W:['左侧','left'],E:['右侧','right']} as Record<string,Pair>)[side];return t([`从${tx(rooms[from].title,locale)}${word[0]}的${areaOf(from)!==areaOf(to)?"外访出口":"门"}前往${tx(rooms[to].title,locale)}`,`From ${tx(rooms[from].title,locale)}, take the ${word[1]} door to ${tx(rooms[to].title,locale)}.`])};
 return <div className="bc-atlas"><div className="bc-atlas-location"><LocateFixed/><span>{t(['你在这里','YOU ARE HERE'])}<strong>{t(rooms[scene].title)}</strong></span></div>
 <button className="bc-area-switch" onClick={()=>setOverview(v=>!v)}>{t(overview?['返回地点内部图','Back to room map']:['地点总览 · 切换地图','Locations · Switch map'])}<MapPin/></button>
 {overview?<section className="bc-area-list">{(Object.keys(areas) as AreaId[]).map(id=><button key={id} onClick={()=>{setArea(id);setDestination(areas[id].rooms.includes(scene)?scene:areas[id].rooms[0]);g.reset();setOverview(false)}}><Building2/><span><strong>{t(areas[id].title)}</strong><small>{areas[id].rooms.length} {t(['个房间',areas[id].rooms.length===1?'room':'rooms'])}{id===areaOf(scene)?t([' · 你在这里',' · You are here']):''}</small></span><ChevronRight/></button>)}</section>:<>
 <h3 className="bc-area-title">{t(areas[area].title)}</h3><nav className="bc-atlas-tools" aria-label={t(['地图操作','Map controls'])}><button onClick={()=>g.reset()}><Maximize/>{t(['全图','Fit'])}</button><button onClick={locate}><LocateFixed/>{t(['定位','Locate'])}</button><button aria-label={t(['缩小地图','Zoom out'])} disabled={g.zoom<=1} onClick={()=>g.scale(g.zoom-.25)}><Minus/></button><button aria-label={t(['放大地图','Zoom in'])} disabled={g.zoom>=3} onClick={()=>g.scale(g.zoom+.25)}><Plus/></button></nav>

 <p className="bc-atlas-hint">{t(['拖动查看 · 双指缩放 · 点房间选择目的地','Drag · Pinch to zoom · Tap a room'])}</p>
 <div className={"bc-atlas-viewport"+(area==='northline'?' bc-atlas-viewport--hq':'')} ref={g.viewport} {...g.handlers}>
 <div className="bc-atlas-world" ref={g.layer}><svg viewBox="0 0 592 390" preserveAspectRatio="none" aria-hidden="true">{edges.filter(e=>e.from<e.to&&areaOf(e.from)===area&&areaOf(e.to)===area).map(e=>{const a=points[e.from],b=points[e.to],i=route?.indexOf(e.from)??-1,active=i>=0&&(route?.[i+1]===e.to||route?.[i-1]===e.to);return <path key={e.id} data-route={active} d={`M${a} L${b}`}/>})}</svg>
 {areas[area].rooms.map(id=>rooms[id]).map(room=>{const I=icons[room.id],p=points[room.id],step=route?.indexOf(room.id)??-1;return <button key={room.id} data-room={room.id} aria-current={room.id===scene?'location':undefined} aria-pressed={room.id===destination} onClick={()=>setDestination(room.id)} style={{left:p[0]/592*100+'%',top:p[1]/390*100+'%'}}><I/><strong>{t(mapLabels[room.id])}</strong>{step>0&&<small>{step}</small>}</button>})}</div></div></>}
 <section className="bc-atlas-directions" aria-live="polite"><small>{t(destination===scene?['当前位置','CURRENT LOCATION']:['目的地','DESTINATION'])}</small><h3>{t(rooms[destination].title)}</h3><button className="bc-map-travel" disabled={status!=='ready'} onClick={()=>onTravel(destination)}>{t(status==='ready'?['前往这里','Go here']:status==='current'?['你在这里','You are here']:status==='unvisited'?['首次到访后解锁','Visit once to unlock']:status==='assignment'?['先在办公室接受项目','Accept the assignment first']:['暂时无法前往','Unavailable'])}<ChevronRight/></button>{steps.length?<details key={destination}><summary>{t(['步行路线','Walking route'])} · {steps.length}</summary><ol>{steps.map(s=><li key={s.from}>{instruction(s.from,s.to)}</li>)}</ol></details>:<p>{t(['点选房间，再点击前往。外部房间首次到访后解锁。','Select a room, then Go here. Visit external rooms once to unlock.'])}</p>}</section></div>
}
