import type {Store} from './state';
import type {Point} from './spatial/world';
export function initializeAuthority():Promise<Store>;
export function authorityStore():Store;
export function readDrafts():Record<string,string>;
export function saveDrafts(drafts:Record<string,string>):void;
export function bindPositionReader(reader:()=>Point):void;
export function residentPose():Point|null;
export function focusResident(id:string|null):Promise<void>;
export function savePosition():Promise<void>;
export function sendIntent(input:any):Promise<any>;
export function recoverAuthority():Promise<any>;
export function selectAuthority(id:string):Promise<Store>;
export function newAuthority():Promise<Store>;
export function authorityHead():any;
export function requestRoom():Promise<any>;
export function pollRoom():Promise<any>;
export function retryRoom():Promise<any>;
export function cancelRoom():void;
export function adoptRoom(candidate:any):Promise<any>;
