export type Locale='zh'|'en';export type Pair=readonly [string,string];export const tx=(p:Pair,l:Locale)=>p[l==='zh'?0:1];
export type RecordId='memo'|'payment'|'contract'|'rollout'|'acceptance'|'appendix'|'cash'|'forecast'|'reference'|'channel';
export type RecordItem={id:RecordId;title:Pair;source:Pair;summary:Pair;body:Pair;tag:Pair};
const recordsBase:RecordItem[]=[
{id:'memo',title:['最后一版投委会摘要','Investment committee brief'],source:['远舟资本 · 项目组 · 周五 16:10','Far Shore Capital · Friday 16:10'],tag:['投资逻辑','THESIS'],summary:['大客户合同 1,200 万元，首款 400 万元。','Anchor contract: ¥12m. First payment: ¥4m.'],body:['栖云为连锁门店提供订货与经营软件。拟投资 3,000 万元，投前估值 1.5 亿元。\n\n本轮核心论据：远禾连锁 32 家门店合同额 1,200 万元；首笔 400 万元已到账；这一案例可以复制到更多连锁客户。\n\n附件中的付款方却写着「桥石商务」，不是远禾。分析师在页边写了一行：钱到账了，但谁在承担购买义务？\n\n你的工作：核实客户使用、收入质量、融资用途，再决定是否支持原价格与条件。','Qiyun sells ordering and operations software to retail chains. Proposed investment: ¥30m at a ¥150m pre-money valuation.\n\nThe thesis: a ¥12m contract covering 32 Yuanhe stores; ¥4m received; a repeatable model for other chains.\n\nThe attachment names BridgeStone Commerce as payer, not Yuanhe. An analyst asks: money arrived, but who bears the obligation to buy?\n\nVerify actual use, revenue quality and cash needs before supporting the price and terms.']},
{id:'payment',title:['首款银行回单','First-payment receipt'],source:['公司授权资料室 · 银行回单','Authorized data room · bank receipt'],tag:['回款','PAYMENT'],summary:['桥石付款 400 万元，附言为项目预付款。','BridgeStone paid ¥4m as a project advance.'],body:['收款人：栖云科技。付款人：桥石商务。金额：400 万元。附言：远禾门店数字化项目预付款。\n\n银行回单证明到账时间与金额，不证明客户最终验收，也不说明款项是否可退。回单编号与补充协议上的项目编号一致。\n\n财务说明：桥石是渠道伙伴，代客户支付。需进一步核对渠道安排与退款条款。','Payee: Qiyun. Payer: BridgeStone Commerce. Amount: ¥4m. Note: advance for Yuanhe store digitization.\n\nThe receipt proves cash arrived. It does not establish final acceptance or whether it is refundable. Its project code matches the supplemental agreement.\n\nFinance says BridgeStone is a channel partner paying on the customer’s behalf. Check the channel arrangement and refund provisions.']},
{id:'contract',title:['远禾主合同','Yuanhe master contract'],source:['公司前台项目台 · 双方签章副本','Project desk · signed copy'],tag:['合同','CONTRACT'],summary:['1,200 万元中，软件订阅 720 万、实施 480 万。','¥7.2m subscription plus ¥4.8m implementation.'],body:['总额 1,200 万元：三年软件订阅 720 万元，门店实施与培训 480 万元。覆盖 32 家门店，分批验收。\n\n附件一：先上线 12 家，剩余 20 家以第二阶段验收为前提。\n\n订阅合同总额、年度经常性收入和当期确认收入是不同口径。不能把三年合同总额全部视为一年可重复的软件收入。\n\n签了合同是真实的，32 家门店全部稳定使用仍需要现场证据。','Total: ¥12m, comprising ¥7.2m for three years of subscription and ¥4.8m for implementation and training. Thirty-two stores, accepted in phases.\n\nSchedule 1: twelve stores first; twenty more depend on phase-two acceptance.\n\nTotal contract value, annual recurring revenue and recognized revenue are different measures. A three-year contract is not one year of recurring software revenue.\n\nThe contract is real. Full deployment still requires operational evidence.']},
{id:'rollout',title:['门店上线清单','Store deployment list'],source:['远禾运营现场 · 本周值班表','Yuanhe operations · this week'],tag:['使用','USAGE'],summary:['32 家签约，12 家上线，6 家持续付费使用。','32 contracted, 12 live, 6 established paid users.'],body:['签约门店 32 家。正式上线 12 家；其中 6 家为此前试点转付费，另外 6 家进入磨合期。其余 20 家仍排期。\n\n值班记录：数据导入比计划慢，员工仍用旧表格交叉检查。两名驻场实施人员一周未回公司。\n\n这不是「没有客户」，但也不是「32 家已经验证」。客户愿意继续试，前提是解决与旧收银系统的数据衔接。','32 stores contracted. Twelve are live: six previous pilots now paying, six in stabilization. Twenty remain scheduled.\n\nData import is behind plan. Staff cross-check against old spreadsheets. Two implementation engineers have spent the week on site.\n\nThere are real customers, but not 32 proven deployments. The customer wants to continue if integration with its legacy tills improves.']},
{id:'acceptance',title:['客户验收意见','Customer acceptance note'],source:['远禾运营经理 · 可供尽调引用','Operations manager · authorized for diligence'],tag:['客户意见','CUSTOMER'],summary:['采购认可方向，运营尚未签署全量验收。','Procurement supports it; full acceptance is unsigned.'],body:['「六家老店订货差错明显少了，这部分价值我们认可。但扩到剩下二十家，我需要看到稳定的数据同步。」\n\n采购与业务团队同意继续合作，不等于公司已经完成第二阶段验收。运营负责人没有承诺放弃退款权。\n\n客户允许你向投委会引用这份说明；无需私自传播客户内部明细。','“Ordering errors fell in the six established stores. We value that. Before expanding to twenty more, I need reliable data synchronization.”\n\nWillingness to continue is not phase-two acceptance. Operations has not waived refund rights.\n\nThe manager authorizes this statement for the committee; private customer records need not circulate.']},
{id:'appendix',title:['项目补充协议','Supplemental agreement'],source:['公司授权资料室 · 第四页附件','Authorized data room · appendix four'],tag:['退款条件','REFUND'],summary:['第二阶段未通过，预付款剩余部分可退。','Unaccepted work leaves a refundable advance.'],body:['第二阶段未在约定日期通过验收，客户可终止未实施门店部分。项目预付款扣除已验收、应付的服务后，余额按约定退回。渠道方收到退款后与客户结算。\n\n400 万元到账是真实事实，但其可自由使用及最终留存程度受合同履行影响。不能直接推断公司造假；需要追问为何投委会摘要没有说明这一条件。','If phase two misses acceptance, the customer may terminate the undeployed portion. After accepted services are deducted, the remaining advance is refundable under the agreement. The channel settles with the customer.\n\nThe ¥4m is real cash, but its ultimate retention depends on performance. This alone does not prove fraud. Ask why the committee brief omitted this condition.']},
{id:'cash',title:['未来四周付款排期','Four-week payment schedule'],source:['财务授权工作台 · 周五 17:05','Finance workstation · Friday 17:05'],tag:['现金','CASH'],summary:['可用资金 87 万，四周刚性支出 230 万。','¥0.87m available against ¥2.3m due.'],body:['账面货币资金并不全部可用。扣除受限保证金后，可用余额 87 万元。未来四周工资、税费及供应商到期款合计 230 万元。\n\n表中尚未计入可能的客户退款。公司正在争取供应商展期，但没有已签署的确认。\n\n这证明近期资金缺口，需要明确融资到账前的应对。它不能单独证明产品无价值。','After restricted deposits, ¥0.87m is available. Payroll, taxes and supplier payments total ¥2.3m over four weeks.\n\nPotential customer refunds are excluded. Supplier extensions are being discussed, but none is signed.\n\nThere is a near-term cash gap requiring a credible response before funding. This does not, by itself, invalidate the product.']},
{id:'forecast',title:['融资用途与现金预测','Use of funds and cash forecast'],source:['创始人共享资料 · 版本 7','Founder’s shared materials · version 7'],tag:['资金用途','USE OF FUNDS'],summary:['预算写着扩张，预测依赖本月底融资到账。','Expansion plan assumes funding closes this month.'],body:['展示页：本轮资金用于研发和市场拓展。\n\n底层预测：融资先覆盖旧有付款义务，再增加实施人员；若月底未到账，下月需推迟部分付款。\n\n管理层按 32 家门店收入测算招聘规模，却没有把第二阶段验收延误作为压力情境。\n\n应将基础偿付、履约投入和新增扩张分别列明。分期交割若首期太少，也可能使履约条件永远无法完成。','Slide: proceeds fund R&D and expansion.\n\nUnderlying forecast: first cover existing obligations, then add implementation staff. Without month-end funding, payments slip next month.\n\nHiring assumes revenue from all 32 stores, without an acceptance-delay stress case.\n\nSeparate existing obligations, delivery investment and expansion. An undersized first tranche could make later milestones impossible.']},
{id:'reference',title:['六家试点复购记录','Six-store renewal record'],source:['客户授权样本 · 已脱敏','Authorized customer sample · anonymized'],tag:['产品价值','PRODUCT VALUE'],summary:['六家连续续费，使用价值有独立证据。','Six stores renewed; value has independent support.'],body:['六家试点门店连续两个周期续费，均有客户直接支付与实际使用记录。\n\n运营反馈：订货差错减少，店长愿意继续使用。样本来自早期配合程度较高的门店，不能机械外推到所有门店。\n\n这项证据支持产品存在真实价值，也解释了为什么暂停投资仍有机会成本。','Six pilot stores renewed for two consecutive periods, with direct customer payments and usage records.\n\nManagers report fewer ordering errors and want to continue. These were cooperative early adopters; results cannot simply be extrapolated to every store.\n\nThis supports genuine product value and explains the opportunity cost of walking away.']},
{id:'channel',title:['渠道服务安排','Channel service arrangement'],source:['授权资料室 · 渠道补充说明','Authorized data room · channel disclosure'],tag:['渠道','CHANNEL'],summary:['桥石收取服务费，代付不等于造假。','BridgeStone earns fees; third-party payment is not proof of fraud.'],body:['桥石负责引荐、实施协调与代结算，并按合同收取服务费。股权登记未显示与栖云控股股东重合。\n\n本次核验未发现资金从栖云转出再转回的证据。但这不能免除对退款条款、净收入和渠道依赖的分析。\n\n分析师此前把「第三方付款」标成「疑似循环回款」；需要更正这一过度判断。','BridgeStone introduces clients, coordinates implementation and handles settlement for a contractual fee. The disclosed ownership does not overlap with Qiyun’s controlling shareholder.\n\nThis review found no evidence of Qiyun sending the same money out and back. Refund terms, net revenue and channel dependence still matter.\n\nThe analyst’s “possible circular payment” label goes beyond the evidence and should be corrected.']}
];
const contextTerms:[string,string][]=[
 ['首期 1,200 万','首期 480 万美元'],['剩余 1,800 万','剩余 720 万美元'],['投前估值调到 1.2 亿，3,000 万一次交割','投前估值调到 4,800 万美元，1,200 万美元一次交割'],
 ['“¥12m first','“$4.8m first'],['remaining ¥18m','remaining $7.2m'],['“¥120m pre-money, ¥30m at closing','“$48m pre-money, $12m at closing'],
 ['远舟资本','北线资本'],['栖云科技','RelayOps'],['栖云','RelayOps'],['远禾','Harbor & Pine'],['桥石商务','BridgeStone Commerce'],['桥石','BridgeStone'],
 ['3,000 万元','1,200 万美元'],['1.5 亿元','6,000 万美元'],['1,200 万元','120 万美元'],['720 万元','72 万美元'],['480 万元','48 万美元'],['400 万元','40 万美元'],['87 万元','8.7 万美元'],['230 万元','23 万美元'],
 ['陈毓','玛拉'],['林澈','丹尼尔'],['许衡','马特奥'],['姜岚','普里娅'],['罗珊','乔丹'],['周宁','艾娃'],
 ['Chen Yu','Mara'],['Lin Che','Daniel'],['Xu Heng','Mateo'],['Jiang Lan','Priya'],['Luo Shan','Jordan'],['Zhou Ning','Ava'],
 ['Far Shore Capital','Northline Capital'],['Far Shore','Northline'],['Qiyun','RelayOps'],['Yuanhe','Harbor & Pine'],
 ['¥30m','$12m'],['¥150m','$60m'],['¥12m','$1.2m'],['¥7.2m','$720k'],['¥4.8m','$480k'],['¥4m','$400k'],['¥0.87m','$87k'],['¥2.3m','$230k']
];
export const localizeContext=(value:string)=>contextTerms.reduce((text,[from,to])=>text.replaceAll(from,to),value);
const mapPair=(pair:Pair):Pair=>[localizeContext(pair[0]),localizeContext(pair[1])];
export const records:RecordItem[]=recordsBase.map(record=>({...record,title:mapPair(record.title),source:mapPair(record.source),summary:mapPair(record.summary),body:mapPair(record.body)}));
export type PersonId='partner'|'analyst'|'founder'|'finance'|'client';
export const people:Record<PersonId,{name:Pair;unknown:Pair;role:Pair;intro:Pair;portrait:number;row:number}>={
partner:{name:['玛拉·埃里森','Mara Ellison'],unknown:['窗边的合伙人','Partner by the window'],role:['北线资本 · 合伙人','Northline · Partner'],portrait:0,row:0,intro:['窗边的女人合上笔记本。她是你的合伙人玛拉·埃里森。「艾娃，这个项目你跟了半年，明早的意见由你来讲。我支持你，但我要知道，你的判断依据是什么。」','Your partner, Mara Ellison, closes her notebook by the window. “Ava, you’ve led this project for six months. Tomorrow, you present. I support you, but I need to understand your evidence.”']},
analyst:{name:['丹尼尔·金','Daniel Kim'],unknown:['抱着材料的分析师','Analyst holding a file'],role:['北线资本 · 分析师','Northline · Analyst'],portrait:1,row:1,intro:['年轻人把圈满红线的摘要递过来。「丹尼尔·金，项目组分析师。合同写的是 Harbor & Pine，回单却是 BridgeStone。我怀疑有问题，但还不敢下结论。」','A young man hands you a marked-up brief. “Daniel Kim, project analyst. Harbor & Pine is on the contract, BridgeStone on the receipt. Something worries me, but I can’t establish what yet.”']},
founder:{name:['马特奥·阿尔瓦雷斯','Mateo Alvarez'],unknown:['卷起袖子的负责人','Executive with rolled sleeves'],role:['RelayOps · 创始人','RelayOps · Founder'],portrait:2,row:2,intro:['卷着袖子的男人从白板前走来。「马特奥·阿尔瓦雷斯，RelayOps 创始人。欢迎你来。我没有取消今晚的客户交付会——你可以看看我们真正忙的是什么。」','The man at the whiteboard walks over. “Mateo Alvarez, founder of RelayOps. Welcome. I kept tonight’s delivery meeting on the calendar. You can see what we’re actually working on.”']},
finance:{name:['普里娅·拉曼','Priya Raman'],unknown:['核对付款的女人','Woman checking payments'],role:['RelayOps · 财务负责人','RelayOps · Finance lead'],portrait:3,row:3,intro:['她把付款表翻到空白的一面，确认你的访客证。「普里娅·拉曼，负责财务。公司已授权你看这批材料。你可以问，但请把账面数字和你自己的推断分开。」','She checks your visitor badge before turning the payment schedule around. “Priya Raman, finance. You’re authorized to inspect these files. Ask anything, but separate recorded figures from your inferences.”']},
client:{name:['乔丹·布鲁克斯','Jordan Brooks'],unknown:['查看门店排期的经理','Manager checking store schedules'],role:['Harbor & Pine · 运营总监','Harbor & Pine · Operations'],portrait:4,row:4,intro:['她指了指桌上的新旧两套操作表。「乔丹·布鲁克斯，负责门店运营。你是来问采购签没签，还是来问店长愿不愿意用？这两件事，答案可能不一样。」','She points to two operating checklists, old and new. “Jordan Brooks, store operations. Are you asking whether procurement signed, or whether store managers want to use it? Those can have different answers.”']}
};
export type Topic={id:string;label:Pair;reply:Pair;requires?:string[];effects?:string[]};
const topicsBase:Record<PersonId,Topic[]>={
partner:[{id:'mandate',label:['你希望我带回什么？','What do you need from me?'],reply:['「先说哪条投资逻辑仍成立，再说哪条变了。把你不知道的地方也写出来。你不是来替我证明原判断正确的。」她把投委会席位留给你。','“Tell me what still holds, then what changed. Include what you don’t know. You’re not here to prove my original view right.” She leaves the committee presentation to you.']},{id:'relationship',label:['你与创始人很熟，会影响决定吗？','Does your history with the founder matter?'],reply:['「认识五年。正因为熟，我更容易替他补全没说出的部分。」她停了一下。「这就是我让你跑现场的原因。别把我的信任算进你的证据。」','“Five years. Familiarity makes it easy to fill in what he leaves unsaid. That’s why I sent you on site. Don’t count my trust as evidence.”']},{id:'committee',label:['什么时候可以提交意见？','When should I submit my view?'],reply:['「资料里的三条判断都能核对。还没查清，也可以向投委会明确提出暂停。附条件推进要先确认创始人愿不愿意接受，条件能不能执行。」','“You can investigate all three questions in your case file. If uncertainty remains, recommend a pause explicitly. Conditional funding requires executable terms that the founder accepts.”']}],
analyst:[{id:'payer',label:['为什么盯着付款方？','Why focus on the payer?'],reply:['「摘要写得像客户已经全额认可。桥石是谁，我还没核实。公司的资料室有回单和渠道说明；如果是正常代付，我会把红字改掉。」','“The brief reads as if the customer has fully accepted. I haven’t verified BridgeStone. Finance has the receipt and channel disclosure. If it’s normal settlement, I’ll correct my annotation.”']},{id:'growth',label:['合同大，为什么还需要去门店？','Why visit stores if the contract is signed?'],reply:['「合同告诉我们双方答应了什么，门店告诉我们交付了什么。三十二家是推广范围，还不一定是今天的使用规模。」','“Contracts show promises. Stores show delivery. Thirty-two is the rollout scope, not necessarily today’s active footprint.”']},{id:'correct',label:['渠道安排已核实，修正你的标注','Correct the circular-payment allegation'],requires:['channel'],effects:['analyst-corrected'],reply:['林澈划掉「循环回款」。「收到。第三方付款不等于造假。真正需要写清的是退款条件和净收入。我会把更正带进材料。」','Lin crosses out “circular payment.” “Understood. Third-party settlement isn’t fraud. Refund exposure and net revenue are the real questions. I’ll correct the committee materials.”']}],
founder:[{id:'value',label:['你最有把握的产品价值是什么？','What gives you confidence in the product?'],reply:['「去问六家老店。我们把订货错误降下来了，所以他们续费。新门店交付确实慢，但我不会说这是一个没人要的产品。」','“Ask the six established stores. Ordering errors fell; they renewed. New deployments are slow, yes. But this isn’t a product nobody wants.”']},{id:'omit',label:['为什么摘要没有写退款条件？','Why omit the refund condition?'],requires:['income'],effects:['founder-disclosed'],reply:['「我以为那是实施合同的常规条款，不是投资逻辑。」他看着补充协议，声音低了下来。「但我知道你们把到账当成了验证。我应该主动解释。」','“I treated it as a routine delivery clause, not part of the thesis.” His voice lowers. “But I knew you were treating cash received as validation. I should have explained.”']},{id:'pressure',label:['融资若延后一个月呢？','What if funding slips a month?'],requires:['funding'],reply:['「我们得与供应商谈展期，先守住交付。裁掉实施团队，省了现金，客户也就没了。你提分期可以，但首期必须够完成交付。」','“We negotiate supplier extensions and protect delivery. Cut implementation staff and we lose the customer. I can discuss tranches, but the first must fund delivery.”']}],
finance:[{id:'scope',label:['这些款项能直接算收入吗？','Can this cash be treated as revenue?'],reply:['「现金、合同额、收入是三个口径。收入确认还得看履约。摘要把它们放得太近了。你可以核对主合同和项目补充协议。」','“Cash, contract value and revenue are different measures. Recognition depends on performance. The brief puts them too close together. Read the contract and its supplement.”']},{id:'payer',label:['桥石为何代付？','Why did BridgeStone pay?'],requires:['payment'],reply:['「渠道服务安排在资料架上。不要只看公司名字不同就说循环回款。如果你找到资金回流证据，我们再谈那个判断。」','“The channel arrangement is on the file shelf. Different names alone don’t establish circular payment. If you find evidence of funds returning, bring it to me.”']},{id:'stress',label:['这份预测没有验收延误情境','The forecast lacks an acceptance-delay case'],requires:['funding'],effects:['finance-stress'],reply:['她把原预算移到一旁。「是。四周支出缺口还不含退款。至少需要单列偿付和履约预算，我愿意每周向董事会报可用现金，前提是创始人同意。」','She sets the budget aside. “Correct. The four-week gap excludes refunds. We need separate obligations and delivery budgets. I’ll report available cash weekly to the board if the founder agrees.”']}],
client:[{id:'real',label:['店长真的愿意继续用吗？','Do managers want to keep using it?'],reply:['「六家老店愿意，那里有人帮他们把流程跑顺了。另外六家还在磨合。我们不是不想扩，只是不想让二十家店一起出问题。」','“The six established stores do. Someone helped them get it working. Six more are settling in. We want expansion, but not twenty stores failing at once.”']},{id:'accept',label:['你会签第二阶段验收吗？','Will you sign phase-two acceptance?'],requires:['rollout'],effects:['client-confirmed'],reply:['「现在不会。先把同步问题解决，连续运行稳定，再按合同验收。这个要求我可以书面给你，但我不会替他们承诺融资后的结果。」','“Not today. Fix synchronization, demonstrate stability, then follow contractual acceptance. I’ll put that in writing. I can’t promise what funding will achieve.”']},{id:'refund',label:['你们一定会要求退款吗？','Will you definitely demand a refund?'],requires:['appendix'],reply:['「不一定。我们愿意把系统做成，但权利不会先放弃。别把『希望继续合作』写成『不可能退款』。」','“Not necessarily. We want this to work, but won’t waive our rights first. Don’t turn willingness to continue into certainty that no refund will occur.”']}]
};
export const topics=Object.fromEntries(Object.entries(topicsBase).map(([person,items])=>[person,items.map(item=>({...item,label:mapPair(item.label),reply:mapPair(item.reply)}))])) as Record<PersonId,Topic[]>;
const findingsBase=[
{id:'usage',title:['增长验证范围','Extent of growth validation'],pair:['contract','rollout'],correct:['合同已签，规模化仍待验证','Signed scope exceeds proven deployment'],wrong:['32 家门店已全部稳定使用','All 32 stores are stable users'],result:['12 家上线、6 家成熟付费。产品有价值，复制速度和实施成本仍需验证。','Twelve live, six established paid stores. Product value exists; rollout speed and delivery costs remain unproven.']},
{id:'income',title:['首款的质量','Quality of the first payment'],pair:['payment','appendix'],correct:['到账属实，但留存附履约条件','Real cash, conditional retention'],wrong:['第三方付款证明公司造假','Third-party payment proves fraud'],result:['回单证明到账，补充协议保留退款权。应修正摘要，不能把代付直接等同造假。','Receipt proves cash arrived; the supplement preserves refund rights. Correct the brief without alleging fraud solely from settlement.']},
{id:'funding',title:['融资先解决什么','What funding must solve first'],pair:['cash','forecast'],correct:['先补近期缺口，再保障交付','Bridge obligations and fund delivery first'],wrong:['全部资金都可用于新增扩张','All proceeds can fund new expansion'],result:['可用 87 万对四周 230 万支出，尚未计潜在退款。先区分偿付、履约与扩张。','¥0.87m available versus ¥2.3m due, before refunds. Separate obligations, delivery and expansion.']}
] as const;
export const findings=findingsBase.map(finding=>({...finding,title:mapPair(finding.title),correct:mapPair(finding.correct),wrong:mapPair(finding.wrong),result:mapPair(finding.result)})) as unknown as typeof findingsBase;

function rawAfterDecision(id:PersonId,j:{save:{facts:Record<string,unknown>}}):Pair{
 const decision=j.save.facts.decision;
 if(id==='partner')return decision==='pause'?['「暂缓也要说明恢复审议的条件。」陈毓把文件留在桌上。「你没有替我们消除不确定性，但至少让我们知道下一步要验证什么。」','“A pause needs conditions for reopening the decision.” Chen leaves the file on the desk. “You made clear what we must verify next.”']:['「决定已经作出，工作还没结束。」陈毓翻回你的依据页。「下次董事会，我会问这些假设有没有变化。」','“The decision is made; the work continues.” Chen turns to your evidence. “At the next board meeting, I’ll ask what changed.”'];
 if(id==='founder')return decision==='pause'?['许衡看了一眼手机，没有立刻回答。「我先去谈供应商展期。你下次回来，希望看到的是新验收单，不是我们的告别信。」','Xu glances at his phone. “I’ll talk to suppliers about extensions. I hope your next visit brings new acceptance records, not our farewell letter.”']:decision==='conditional'?['「条件我接受。也请记住，实施人员不是表格里可以随意延后的数字。」他收起清单，去准备客户会议。','“I accept the terms. Remember that delivery staff are not numbers we can defer indefinitely.” He takes the list to the customer meeting.']:['「谢谢你的信任。」许衡停了一下。「我知道你没有把问题当作不存在。下周的交付进度，我会让你看原表。」','“Thank you for your trust. I know you haven’t dismissed the issues. Next week, you’ll see the original delivery schedule.”'];
 if(id==='finance')return ['姜岚把两张表并排放好。「不管最后怎么投，这张可用现金表都得每天更新。下次看到一个到账数字，先问它背后还有什么义务。」','Jiang lays two schedules side by side. “Whatever the investment decision, available cash needs a daily update. Next time you see cash received, ask what obligations travel with it.”'];
 if(id==='client')return ['「投资的事我不替你判断。」罗珊指向现场还在工作的同事。「系统能不能稳定运行，明早开店我们就知道了。验收还是按约定来。」','“I won’t judge your investment.” Luo points to her team. “We’ll see how the system works when stores open tomorrow. Acceptance still follows the agreement.”'];
 return j.save.facts['analyst-corrected']?['林澈把改好的摘要递来。「『循环回款』已经删掉。我保留了付款方和退款条件，让投委会自己看到事实。下次我会先核对，再画红圈。」','Lin hands over the revised brief. “I removed the circular-payment claim and kept the payer and refund facts. Next time I’ll verify before drawing red circles.”']:['林澈合上文件。「我还欠这份材料一次核对。看到异常和证明造假，确实不是同一件事。」','Lin closes the file. “I still owe these materials another check. An anomaly and proof of fraud are different things.”'];
}
export function afterDecision(id:PersonId,j:{save:{facts:Record<string,unknown>}}):Pair{return mapPair(rawAfterDecision(id,j))}
