// Only definitive no-commit rejections. Timeouts, transport failures and
// MODEL_CALL_PENDING_OR_INTERRUPTED retain their original action envelope.
export const financeTerminalErrors=Object.freeze([
 'OUT_OF_REACH','TARGET_OUT_OF_REACH','OPENING_REQUIRED','PROLOGUE_REQUIRED',
 'INTRODUCTION_REQUIRED','DIALOGUE_UNAVAILABLE','MODEL_BUDGET_EXHAUSTED',
 'AI_DIALOGUE_DAILY_LIMIT','AI_ROOM_DAILY_LIMIT','AI_COOLDOWN','AI_REQUEST_IN_PROGRESS',
 'AI_QUEUE_FULL','AI_QUEUE_TIMEOUT','AI_RETRY_NEW_REQUEST','AI_REQUEST_CONFLICT',
 'MODEL_TIMEOUT','MODEL_OUTPUT_INVALID','MODEL_HTTP_ERROR','MODEL_CALL_FAILED','INVALID_NARRATION','SERVICE_BUSY',
]);
