import {canArchive} from './headquarters';
import {chapterEnabled,chapterReviewed,roomRevision} from './chapter';
import {createInitialSave,applyParsedScene} from './engine-source/engine/reducer';import type {StoryCartridge,StorySave,DomainEffect} from './engine-source/types';
import {records,findings,type Locale,type PersonId} from './content';import {spawn,world,type SceneId} from './world';import {walkable,type Point} from './spatial/world';import {GAME_UUID} from './game-id';
export const cartridge:StoryCartridge={schemaVersion:1,id:'before-the-close',locale:'en',coverImage:'./art/platform-v1/poster.png',copy:{title:'Before the Close',subtitle:'A Northline Capital case',promise:'',enter:'Begin',continue:'Continue',customAction:'',itemImagingTitle:'',itemImagingBody:''},theme:{outer:'#142b35',surface:'#233b42',paper:'#f2eddf',ink:'#243941',muted:'#687a7d',accent:'#b48b50',danger:'#9c5048',gold:'#b48b50',material:'apartment'},audioTheme:{material:'apartment',bpm:76,rootHz:110,scale:[0,3,7],levels:{music:.15,ambient:0,sfx:.2,master:.5},tension:[]},statDefinitions:[{id:'research',label:'Research',initial:0,min:0,max:100},{id:'trust',label:'Trust',initial:0,min:0,max:100},{id:'risk',label:'Risk',initial:0,min:0,max:100}] as StoryCartridge['statDefinitions'],drawerLabels:{party:'People',map:'Map',inventory:'Evidence',log:'Log'},opening:{location:'fund',time:'16:40',objective:'Review the committee brief',imagePrompt:'',blocks:[],choices:[]},characters:[],initialMap:[],initialInventory:[],demoTurns:[]};
export type ChatTurn={id?:string;person:PersonId;question:string;reply:string;topicKey?:string};
export type Journey={id:string;created:number;title:string;scene:SceneId;position:Point;save:StorySave;history:ChatTurn[];opened:boolean;chapterVersion?:1;projectId?:'relayops';storyMinute?:number;decisionSnapshot?:{findings:string[];terms:unknown}};
export type Store={version:1;active:string;journeys:Journey[];locale:Locale;localeMode:'system'|'manual';muted:boolean};
export function systemLocale():Locale{if(typeof navigator==='undefined')return'en';return(navigator.languages?.[0]||navigator.language||'en').toLowerCase().startsWith('zh')?'zh':'en'}
export function newJourney():Journey{return{id:crypto.randomUUID(),created:Date.now(),title:'',scene:'study',position:spawn('study'),save:createInitialSave(cartridge),history:[],opened:false,projectId:'relayops',chapterVersion:1,storyMinute:1000}}
export function newStore():Store{const j=newJourney();return{version:1,active:j.id,journeys:[j],locale:systemLocale(),localeMode:'system',muted:false}}
export function has(j:Journey,id:string){return Boolean(j.save.facts[id])}
export function facts(j:Journey,effects:DomainEffect[],text:string):Journey{const save=applyParsedScene(j.save,{blocks:[{id:crypto.randomUUID(),kind:'narration',text}],commands:[],raw:text},cartridge,text,undefined,undefined,undefined,{status:'accepted',ruleId:'authored-investigation',intent:'investigate',effects,reasons:[],successText:text,successChoices:[],continuation:'resume'});return{...j,save}}
export function mark(j:Journey,id:string,text=''){return facts(j,[{type:'fact',id,value:true}],text||id)}
export function collect(j:Journey,id:string){if(!records.some(r=>r.id===id))return j;const revision=roomRevision(j,id);let next=has(j,id)?j:mark(j,id,'取得资料：'+id);if(revision&&!has(next,revision.flag))next=mark(next,revision.flag,revision.title[1]);return next}
export function conclude(j:Journey,id:string,selected:string[],correct:boolean){const f=findings.find(f=>f.id===id);if(!f||!correct||!f.pair.every(p=>selected.includes(p)&&has(j,p))||selected.length!==2)return j;return mark(j,id,f.result[0])}
export function canNegotiate(j:Journey){return findings.every(f=>has(j,f.id))&&has(j,'reference')&&has(j,'client-confirmed')&&has(j,'met-founder')}
export function negotiate(j:Journey,term:'tranche'|'reprice'){if(!canNegotiate(j)||has(j,'decision'))return j;return facts(j,[{type:'fact',id:'terms',value:term}],term==='tranche'?'创始人接受首期保障交付、后续按验收分期与现金披露':'创始人接受调整价格，明确资金用途及现金披露')}
export type Decision='proceed'|'conditional'|'pause';
export function decide(j:Journey,decision:Decision){if((decision!=='pause'&&chapterEnabled(j)&&!chapterReviewed(j))||has(j,'decision')||!has(j,'memo')||!has(j,'met-partner')||(decision==='conditional'&&!j.save.facts.terms))return j;return {...facts(j,[{type:'fact',id:'decision',value:decision},{type:'session',ended:true}],`投委会意见：${decision}`),chapterVersion:1 as const,decisionSnapshot:{findings:findings.filter(f=>has(j,f.id)).map(f=>f.id),terms:j.save.facts.terms}}}
export function load():Store{const raw=alteruLocalStorage.getItem('before-the-close');if(!raw)return newStore();try{const s=JSON.parse(raw);if(s.version!==1||!Array.isArray(s.journeys)||!s.journeys.some((j:Journey)=>j.id===s.active)||!s.journeys.every((j:Journey)=>j&&typeof j.id==='string'&&['lobby','fund','office','records','client','delivery','channel','meeting','study','archive','partnerroom'].includes(j.scene)&&Number.isFinite(j.position?.x)&&Number.isFinite(j.position?.y)&&j.save?.facts&&Array.isArray(j.history)))throw Error('version');const localeMode=s.localeMode==='manual'?'manual':'system';return{...s,journeys:s.journeys.map((j:Journey)=>walkable(world,j.scene,j.position)?j:{...j,position:spawn(j.scene)}),localeMode,locale:localeMode==='system'?systemLocale():s.locale}}catch{throw Error('SAVE_READ_FAILED')}}
export function persist(store:Store){alteruLocalStorage.setItem('before-the-close',JSON.stringify(store))}
export {GAME_UUID};

export function activateJourney(s:Store,id:string,at:Point):Store{if(!s.journeys.some(x=>x.id===id))return s;return {...s,active:id,journeys:s.journeys.map(x=>x.id===s.active?{...x,position:{...at}}:x)}}
export function appendJourney(s:Store,j:Journey,at:Point):Store{const saved=activateJourney(s,s.active,at);return {...saved,active:j.id,journeys:[j,...saved.journeys]}}
export function arriveAt(j:Journey,scene:SceneId,at:Point):Journey{const time={lobby:1000,fund:1000,office:1040,records:1085,client:1150,delivery:1100,channel:1120,meeting:1000,study:1000,archive:1000,partnerroom:1000};return {...j,scene,position:{...at},storyMinute:Math.max(j.storyMinute??time[j.scene],time[scene])}}

export function archiveJourney(j:Journey){return canArchive(j)&&!has(j,'case-archived')?mark(j,'case-archived'):j}
