import {createInitialSave,applyParsedScene} from './engine-source/engine/reducer';import type {StoryCartridge,StorySave,DomainEffect} from './engine-source/types';
import {records,findings,type Locale,type PersonId} from './content';import {spawn,type SceneId} from './world';import type {Point} from './spatial/world';import {GAME_UUID} from './game-id';
export const cartridge:StoryCartridge={schemaVersion:1,id:'before-the-close',locale:'zh',coverImage:'./poster.png',copy:{title:'交割之前',subtitle:'Before the Close',promise:'',enter:'开始',continue:'继续',customAction:'',itemImagingTitle:'',itemImagingBody:''},theme:{outer:'#142b35',surface:'#233b42',paper:'#f2eddf',ink:'#243941',muted:'#687a7d',accent:'#b48b50',danger:'#9c5048',gold:'#b48b50',material:'apartment'},audioTheme:{material:'apartment',bpm:76,rootHz:110,scale:[0,3,7],levels:{music:.15,ambient:0,sfx:.2,master:.5},tension:[]},statDefinitions:[{id:'research',label:'调查',initial:0,min:0,max:100},{id:'trust',label:'信任',initial:0,min:0,max:100},{id:'risk',label:'风险',initial:0,min:0,max:100}] as StoryCartridge['statDefinitions'],drawerLabels:{party:'人物',map:'地图',inventory:'资料',log:'记录'},opening:{location:'fund',time:'16:40',objective:'核对投委会摘要',imagePrompt:'',blocks:[],choices:[]},characters:[],initialMap:[],initialInventory:[],demoTurns:[]};
export type ChatTurn={person:PersonId;question:string;reply:string};
export type Journey={id:string;created:number;title:string;scene:SceneId;position:Point;save:StorySave;history:ChatTurn[];opened:boolean;decisionSnapshot?:{findings:string[];terms:unknown}};
export type Store={version:1;active:string;journeys:Journey[];locale:Locale;muted:boolean};
export function newJourney():Journey{return{id:crypto.randomUUID(),created:Date.now(),title:'',scene:'fund',position:spawn('fund'),save:createInitialSave(cartridge),history:[],opened:false}}
export function newStore():Store{const j=newJourney();return{version:1,active:j.id,journeys:[j],locale:'zh',muted:false}}
export function has(j:Journey,id:string){return Boolean(j.save.facts[id])}
export function facts(j:Journey,effects:DomainEffect[],text:string):Journey{const save=applyParsedScene(j.save,{blocks:[{id:crypto.randomUUID(),kind:'narration',text}],commands:[],raw:text},cartridge,text,undefined,undefined,undefined,{status:'accepted',ruleId:'authored-investigation',intent:'investigate',effects,reasons:[],successText:text,successChoices:[],continuation:'resume'});return{...j,save}}
export function mark(j:Journey,id:string,text=''){return facts(j,[{type:'fact',id,value:true}],text||id)}
export function collect(j:Journey,id:string){if(!records.some(r=>r.id===id)||has(j,id))return j;return mark(j,id,'取得资料：'+id)}
export function conclude(j:Journey,id:string,selected:string[],correct:boolean){const f=findings.find(f=>f.id===id);if(!f||!correct||!f.pair.every(p=>selected.includes(p)&&has(j,p))||selected.length!==2)return j;return mark(j,id,f.result[0])}
export function canNegotiate(j:Journey){return findings.every(f=>has(j,f.id))&&has(j,'reference')&&has(j,'client-confirmed')&&has(j,'met-founder')}
export function negotiate(j:Journey,term:'tranche'|'reprice'){if(!canNegotiate(j))return j;return facts(j,[{type:'fact',id:'terms',value:term}],term==='tranche'?'创始人接受首期保障交付、后续按验收分期与现金披露':'创始人接受调整价格，明确资金用途及现金披露')}
export type Decision='proceed'|'conditional'|'pause';
export function decide(j:Journey,decision:Decision){if(has(j,'decision')||!has(j,'memo')||!has(j,'met-partner')||(decision==='conditional'&&!j.save.facts.terms))return j;return {...facts(j,[{type:'fact',id:'decision',value:decision},{type:'session',ended:true}],`投委会意见：${decision}`),decisionSnapshot:{findings:findings.filter(f=>has(j,f.id)).map(f=>f.id),terms:j.save.facts.terms}}}
export function load():Store{const raw=alteruLocalStorage.getItem('before-the-close');if(!raw)return newStore();try{const s=JSON.parse(raw);if(s.version!==1||!Array.isArray(s.journeys)||!s.journeys.some((j:Journey)=>j.id===s.active)||!s.journeys.every((j:Journey)=>j&&typeof j.id==='string'&&['fund','office','records','client'].includes(j.scene)&&Number.isFinite(j.position?.x)&&Number.isFinite(j.position?.y)&&j.save?.facts&&Array.isArray(j.history)))throw Error('version');return s}catch{throw Error('SAVE_READ_FAILED')}}
export function persist(store:Store){alteruLocalStorage.setItem('before-the-close',JSON.stringify(store))}
export {GAME_UUID};
